version: '3.8'
networks:
  dev:


services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
      - db
    networks:
      - dev

  backend:
    build: ./backend
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; cd src && alembic upgrade head && uvicorn main:app --host 0.0.0.0'
    volumes:
      - .:/backend
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://postgres:12345@db:5432/neuro-ark
    depends_on:
      - db
    networks:
      - dev
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = 12345
      - POSTGRES_DB = neuro-ark
      - POSTGRES_HOST = 172.20.0.3
    
    networks:
      - dev
    
  
  frontend:
    build:
      context: ./frontend
    networks:
      - dev

volumes:
      postgres_data:
