version: '3.8'
networks:
  dev:


services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
      - db
    networks:
      - dev

  backend:
    build: ./backend
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; cd src && alembic upgrade head && uvicorn main:app --host 0.0.0.0'
    volumes:
      - .:/backend
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://postgres:12345@db:5432/neuro-ark
    depends_on:
      - db
    networks:
      - dev
  db:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "neuro-ark"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - habrdb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d neuro-ark"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    
    networks:
      - dev
    
  
  frontend:
    build:
      context: ./frontend
    networks:
      - dev

volumes:
      postgres_data:
